# File used by VCFanno to define how a VCF file should be annotated

[[annotation]]
file="annotations/gnomad.genomes.sites.merged.AF_AC_AN_only.vcf.gz"
fields = ["AF", "AC", "AN", "POPMAX", "AF_POPMAX", "AC_POPMAX", "AN_POPMAX"]
ops=["self", "self", "self", "self", "self", "self", "self"]
names=["gn_af", "gn_ac", "gn_an", "gn_popmax", "gn_pm_af", "gn_pm_ac", "gn_pm_an"]

[[annotation]]
file="annotations/cadd_v1.3.vcf.gz"
names=["cadd_phred", "cadd_raw"]
ops=["self", "self"]
fields=["phred", "raw"]
# Used process outlined on https://github.com/brentp/vcfanno/blob/master/docs/examples/cadd.md to create CADD vcf file from original download

[[annotation]]
file="annotations/reheadered.MGRB.vcf.gz"
fields=["AC", "AF"]
ops=["self", "self"]
names=["mgrb_ac", "mgrb_af"]

[[annotation]]
file="annotations/dbscSNV1.1.vcf.gz"
fields = ["ada_score", "rf_score"]
ops=["self", "self"]
names=["dbscSNV_ada_score", "dbscSNV_rf_score"]

[[annotation]]
file="annotations/hg19_spidex.sorted.vcf.gz"
fields = ["dpsi_max_tissue", "dpsi_zscore"]
ops=["self", "self"]
names=["SPIDEX_dpsi_max_tissue", "SPIDEX_dpsi_zscore"]

[[annotation]]
file="annotations/gencode_v26_branchpoints.csv.liftedtohg19.sorted.vcf.gz"
fields = ["branchpoint_prob", "U2_binding_energy"]
ops=["self", "self"]
names=["branchpointer_branchpoint_prob", "branchpointer_U2_binding_energy"]
